package test;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

import java.security.InvalidKeyException;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;
import java.security.SignatureException;
import java.security.UnrecoverableKeyException;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.util.Arrays;
import java.util.Base64;
import java.util.Enumeration;




public class TestFirma {

	public static boolean validar(KeyStore ks, String alias, String algoritmo,byte[] datos, byte[] firma) throws KeyStoreException, InvalidKeyException, NoSuchAlgorithmException, SignatureException {
		   Certificate cert = ks.getCertificate(alias);

		   return validar(cert.getPublicKey(),algoritmo,datos,firma);
		}
	
	public static boolean validar(PublicKey pKey, String algoritmo,byte[] datos, byte[] firma) throws NoSuchAlgorithmException, InvalidKeyException, SignatureException {
		   if(algoritmo == null || algoritmo.length() <= 0)
		      algoritmo = "SHA1withRSA";
		   
		   Signature dsa = Signature.getInstance(algoritmo);
		   
		   dsa.initVerify(pKey);
		   dsa.update(datos);
		   
		   return dsa.verify(firma);
		}
	
	public static byte[] firmar(PrivateKey pKey, String algoritmo , byte[] toSign) throws InvalidKeyException, SignatureException , NoSuchAlgorithmException {
		   if(algoritmo == null || algoritmo.length() <= 0)
		      algoritmo = "SHA1withRSA";
		   
		   System.out.println("algoritmo:"+algoritmo);
		   Signature dsa = Signature.getInstance(algoritmo);
		   
		   dsa.initSign(pKey);
		   
		   dsa.update(toSign);
		   
		   //return dsa.verify(signature)
		   
		   return dsa.sign();
	}
	
	public static PrivateKey getPrivateKeyfromKeyStore(File keyStore, String ksPassword, String tipoKeyStore, String algoritmo, String alias, String password) throws KeyStoreException, NoSuchAlgorithmException, CertificateException, IOException, UnrecoverableKeyException {
		   if(tipoKeyStore == null || tipoKeyStore.length() <= 0)
		      tipoKeyStore = "JKS";
		   
		   KeyStore ks = KeyStore.getInstance(tipoKeyStore);
		   System.out.println("ks "+ks.getType());
		   ks.load(new FileInputStream(keyStore),ksPassword.toCharArray());
		   
		   return getPrivateKeyfromKeyStore(ks,algoritmo,alias,password);
		   
		}
	
	
	public static PrivateKey getPrivateKeyfromKeyStore(KeyStore keyStore, String algoritmo, String alias, String password) throws KeyStoreException, NoSuchAlgorithmException, CertificateException, UnrecoverableKeyException {
		   if(algoritmo == null || algoritmo.length() <= 0)
			   algoritmo = "RSA";
			   //algoritmo = "SHA1withRSA";
			   
		   
//		   System.out.println("alias "+alias + " password " +password + " algoritmo " + algoritmo);
//		   System.out.println("keyStore.containsAlias(alias) "+keyStore.containsAlias(alias));
//		   System.out.println("keyStore.isKeyEntry(alias) "+keyStore.isKeyEntry(alias));
//		   System.out.println("keyStore.isCertificateEntry(alias) "+keyStore.isCertificateEntry(alias));
//		   System.out.println("keyStore.aliases() "+Arrays.asList(keyStore.aliases()));
//		   
		   Enumeration<String> e = keyStore.aliases();
		   while (e.hasMoreElements()) {
               System.out.print(e.nextElement() + "");
               System.out.println();
           }
		   
		   Certificate cert = (Certificate) keyStore.getCertificate(alias);
		   //System.out.println(cert.getPublicKey());
		   
		   return (PrivateKey)keyStore.getKey(alias,password.toCharArray());
		   
	}
	
	
	
	public static void main(String[] args) {
		
		PrivateKey privKey = null;
		try {           
//			String test= "yo soy vkn";
//			System.out.println("test:"+test);
//			byte[] b64 = Base64.getEncoder().encode(test.getBytes("UTF-8"));
//			System.out.println("b64:"+new String(b64));
//			byte[] decode = Base64.getDecoder().decode(b64);
//			System.out.println("decode:"+new String(decode));
//			
			
			File fileRepositorio =new File("src/main/resources/entelCertificado.store"); 
					//ResourceUtils.getFile("classpath:certificate.cer");//new File("certificate.cer");
			
			//String data = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PFNIT1BQSU5HX0NBUlQ+PENVU1RPTUVSX0lEPjE4Nzg3MjgzLTk8L0NVU1RPTUVSX0lEPjxERUxJVkVSWV9BTU9VTlQ+MDwvREVMSVZFUllfQU1PVU5UPjxPUkRFUl9JRD42ODgzMjY1MTM8L09SREVSX0lEPjxQUk9EVUNUX0RFVEFJTD48UFJPRFVDVD48QU1PVU5UPjc0Mzc2MDwvQU1PVU5UPjxQUk9EVUNUX05BTUU+SHVhd2VpIFA0MCBQcm8sIDI1NiBHQiBBenVsPC9QUk9EVUNUX05BTUU+PFFVQU5USVRZPjE8L1FVQU5USVRZPjxTS1U+MTMzMzA3PC9TS1U+PC9QUk9EVUNUPjwvUFJPRFVDVF9ERVRBSUw+PFJFVFVSTl9VUkw+aHR0cHM6Ly9wb3J0YWxwcmVwcm9kLmVudGVsLmNsL3BlcnNvbmFzL3BsYW5lc1YyL3BheW1lbnQ8L1JFVFVSTl9VUkw+PFNFU1NJT05fSUQ+MjAyMzA4MDQxNjU5MTQwMTwvU0VTU0lPTl9JRD48VE9UQUxfQU1PVU5UPjc0Mzc2MDwvVE9UQUxfQU1PVU5UPjxUUkFOU0FDVElPTl9JREVOVElGSUVSPjIwMjMwODA0MTY1OTE0MDE8L1RSQU5TQUNUSU9OX0lERU5USUZJRVI+PFRSQU5TQUNUSU9OX1RJTUVTVEFNUD4yMDIzMDgwNDE2NTkxNDwvVFJBTlNBQ1RJT05fVElNRVNUQU1QPjxUUkFOU0FDVElPTl9UWVBFPjI8L1RSQU5TQUNUSU9OX1RZUEU+PFNPQ0lFVFk+UENTPC9TT0NJRVRZPjwvU0hPUFBJTkdfQ0FSVD4=";
			//String data = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PFNIT1BQSU5HX0NBUlQ+PENVU1RPTUVSX0lEPjE3NzAzMjQyLTU8L0NVU1RPTUVSX0lEPjxERUxJVkVSWV9BTU9VTlQ+MDwvREVMSVZFUllfQU1PVU5UPjxPUkRFUl9JRD42ODgxNjkxOTg8L09SREVSX0lEPjxQUk9EVUNUX0RFVEFJTD48UFJPRFVDVD48QU1PVU5UPjM0OTkwPC9BTU9VTlQ+PFBST0RVQ1RfTkFNRT5IVUFXRUkgU01BUlRXQVRDSCBXQVRDSCBGSVQgTkVHUk8sIE5lZ3JvPC9QUk9EVUNUX05BTUU+PFFVQU5USVRZPjE8L1FVQU5USVRZPjxTS1U+MVNXMDQ1NTY8L1NLVT48L1BST0RVQ1Q+PFBST0RVQ1Q+PEFNT1VOVD4zOTgwPC9BTU9VTlQ+PFBST0RVQ1RfTkFNRT5Qcm9ncmFtYWRvIERlbGl2ZXJ5PC9QUk9EVUNUX05BTUU+PFFVQU5USVRZPjE8L1FVQU5USVRZPjxTS1U+UE9ETFYwMDAzPC9TS1U+PC9QUk9EVUNUPjxQUk9EVUNUPjxBTU9VTlQ+LTE5OTA8L0FNT1VOVD48UFJPRFVDVF9OQU1FPkRlc2N1ZW50byBwYXJhIFByb2dyYW1hZG8gRGVsaXZlcnk8L1BST0RVQ1RfTkFNRT48UVVBTlRJVFk+MTwvUVVBTlRJVFk+PFNLVT4wPC9TS1U+PC9QUk9EVUNUPjxQUk9EVUNUPjxBTU9VTlQ+NTk4MDwvQU1PVU5UPjxQUk9EVUNUX05BTUU+RXhwcmVzcyBEZWxpdmVyeTwvUFJPRFVDVF9OQU1FPjxRVUFOVElUWT4xPC9RVUFOVElUWT48U0tVPlBPRExWMDAwMzwvU0tVPjwvUFJPRFVDVD48UFJPRFVDVD48QU1PVU5UPi0yOTkwPC9BTU9VTlQ+PFBST0RVQ1RfTkFNRT5EZXNjdWVudG8gcGFyYSBFeHByZXNzIERlbGl2ZXJ5PC9QUk9EVUNUX05BTUU+PFFVQU5USVRZPjE8L1FVQU5USVRZPjxTS1U+MDwvU0tVPjwvUFJPRFVDVD48L1BST0RVQ1RfREVUQUlMPjxSRVRVUk5fVVJMPmh0dHA6Ly9sb2NhbGhvc3QvcGVyc29uYXMvcGxhbmVzVjIvcGF5bWVudDwvUkVUVVJOX1VSTD48U0VTU0lPTl9JRD4yMDIzMDgwNzE1NDMwMTAxPC9TRVNTSU9OX0lEPjxUT1RBTF9BTU9VTlQ+MzQ5OTA8L1RPVEFMX0FNT1VOVD48VFJBTlNBQ1RJT05fSURFTlRJRklFUj4yMDIzMDgwNzE1NDMwMTAxPC9UUkFOU0FDVElPTl9JREVOVElGSUVSPjxUUkFOU0FDVElPTl9USU1FU1RBTVA+MjAyMzA4MDcxNTQzMDE8L1RSQU5TQUNUSU9OX1RJTUVTVEFNUD48VFJBTlNBQ1RJT05fVFlQRT4yPC9UUkFOU0FDVElPTl9UWVBFPjxTT0NJRVRZPlBDUzwvU09DSUVUWT48L1NIT1BQSU5HX0NBUlQ+";
			//String data = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PFNIT1BQSU5HX0NBUlQ+PENVU1RPTUVSX0lEPjE3NzAzMjQyLTU8L0NVU1RPTUVSX0lEPjxERUxJVkVSWV9BTU9VTlQ+MDwvREVMSVZFUllfQU1PVU5UPjxPUkRFUl9JRD42ODgxNjkxOTg8L09SREVSX0lEPjxQUk9EVUNUX0RFVEFJTD48UFJPRFVDVD48QU1PVU5UPjM0OTkwPC9BTU9VTlQ+PFBST0RVQ1RfTkFNRT5IVUFXRUkgU01BUlRXQVRDSCBXQVRDSCBGSVQgTkVHUk8sIE5lZ3JvPC9QUk9EVUNUX05BTUU+PFFVQU5USVRZPjE8L1FVQU5USVRZPjxTS1U+MVNXMDQ1NTY8L1NLVT48L1BST0RVQ1Q+PFBST0RVQ1Q+PEFNT1VOVD4zOTgwPC9BTU9VTlQ+PFBST0RVQ1RfTkFNRT5Qcm9ncmFtYWRvIERlbGl2ZXJ5PC9QUk9EVUNUX05BTUU+PFFVQU5USVRZPjE8L1FVQU5USVRZPjxTS1U+UE9ETFYwMDAzPC9TS1U+PC9QUk9EVUNUPjxQUk9EVUNUPjxBTU9VTlQ+LTE5OTA8L0FNT1VOVD48UFJPRFVDVF9OQU1FPkRlc2N1ZW50byBwYXJhIFByb2dyYW1hZG8gRGVsaXZlcnk8L1BST0RVQ1RfTkFNRT48UVVBTlRJVFk+MTwvUVVBTlRJVFk+PFNLVT4wPC9TS1U+PC9QUk9EVUNUPjxQUk9EVUNUPjxBTU9VTlQ+NTk4MDwvQU1PVU5UPjxQUk9EVUNUX05BTUU+RXhwcmVzcyBEZWxpdmVyeTwvUFJPRFVDVF9OQU1FPjxRVUFOVElUWT4xPC9RVUFOVElUWT48U0tVPlBPRExWMDAwMzwvU0tVPjwvUFJPRFVDVD48UFJPRFVDVD48QU1PVU5UPi0yOTkwPC9BTU9VTlQ+PFBST0RVQ1RfTkFNRT5EZXNjdWVudG8gcGFyYSBFeHByZXNzIERlbGl2ZXJ5PC9QUk9EVUNUX05BTUU+PFFVQU5USVRZPjE8L1FVQU5USVRZPjxTS1U+MDwvU0tVPjwvUFJPRFVDVD48L1BST0RVQ1RfREVUQUlMPjxSRVRVUk5fVVJMPmh0dHA6Ly9sb2NhbGhvc3QvcGVyc29uYXMvcGxhbmVzVjIvcGF5bWVudDwvUkVUVVJOX1VSTD48U0VTU0lPTl9JRD4yMDIzMDgwNzE5MjcwOTAxPC9TRVNTSU9OX0lEPjxUT1RBTF9BTU9VTlQ+MzQ5OTA8L1RPVEFMX0FNT1VOVD48VFJBTlNBQ1RJT05fSURFTlRJRklFUj4yMDIzMDgwNzE5MjcwOTAxPC9UUkFOU0FDVElPTl9JREVOVElGSUVSPjxUUkFOU0FDVElPTl9USU1FU1RBTVA+MjAyMzA4MDcxOTI3MDk8L1RSQU5TQUNUSU9OX1RJTUVTVEFNUD48VFJBTlNBQ1RJT05fVFlQRT4yPC9UUkFOU0FDVElPTl9UWVBFPjxTT0NJRVRZPlBDUzwvU09DSUVUWT48L1NIT1BQSU5HX0NBUlQ+";
			//String data = "<SHOPPING_CART><CUSTOMER_ID>17703242-5</CUSTOMER_ID><DELIVERY_AMOUNT>0</DELIVERY_AMOUNT><ORDER_ID>688169198</ORDER_ID><PRODUCT_DETAIL><PRODUCT><AMOUNT>34990</AMOUNT><PRODUCT_NAME>HUAWEI SMARTWATCH WATCH FIT NEGRO, Negro</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>1SW04556</SKU></PRODUCT><PRODUCT><AMOUNT>3980</AMOUNT><PRODUCT_NAME>Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-1990</AMOUNT><PRODUCT_NAME>Descuento para Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT><PRODUCT><AMOUNT>5980</AMOUNT><PRODUCT_NAME>Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-2990</AMOUNT><PRODUCT_NAME>Descuento para Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT></PRODUCT_DETAIL><RETURN_URL>http://localhost/personas/planesV2/payment</RETURN_URL><SESSION_ID>2023080719331201</SESSION_ID><TOTAL_AMOUNT>34990</TOTAL_AMOUNT><TRANSACTION_IDENTIFIER>2023080719331201</TRANSACTION_IDENTIFIER><TRANSACTION_TIMESTAMP>20230807193312</TRANSACTION_TIMESTAMP><TRANSACTION_TYPE>2</TRANSACTION_TYPE></SHOPPING_CART>";
			//String data = "<SHOPPING_CART><CUSTOMER_ID>17703242-5</CUSTOMER_ID><DELIVERY_AMOUNT>0</DELIVERY_AMOUNT><ORDER_ID>688169198</ORDER_ID><PRODUCT_DETAIL><PRODUCT><AMOUNT>34990</AMOUNT><PRODUCT_NAME>HUAWEI SMARTWATCH WATCH FIT NEGRO, Negro</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>1SW04556</SKU></PRODUCT><PRODUCT><AMOUNT>3980</AMOUNT><PRODUCT_NAME>Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-1990</AMOUNT><PRODUCT_NAME>Descuento para Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT><PRODUCT><AMOUNT>5980</AMOUNT><PRODUCT_NAME>Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-2990</AMOUNT><PRODUCT_NAME>Descuento para Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT></PRODUCT_DETAIL><RETURN_URL>http://localhost/personas/planesV2/payment</RETURN_URL><SESSION_ID>2023080721194801</SESSION_ID><TOTAL_AMOUNT>34990</TOTAL_AMOUNT><TRANSACTION_IDENTIFIER>2023080721194801</TRANSACTION_IDENTIFIER><TRANSACTION_TIMESTAMP>20230807211948</TRANSACTION_TIMESTAMP><TRANSACTION_TYPE>2</TRANSACTION_TYPE><SOCIETY>PCS</SOCIETY></SHOPPING_CART>";
			//String data = "<SHOPPING_CART><CUSTOMER_ID>17703242-5</CUSTOMER_ID><DELIVERY_AMOUNT>0</DELIVERY_AMOUNT><ORDER_ID>688169198</ORDER_ID><PRODUCT_DETAIL><PRODUCT><AMOUNT>34990</AMOUNT><PRODUCT_NAME>HUAWEI SMARTWATCH WATCH FIT NEGRO, Negro</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>1SW04556</SKU></PRODUCT><PRODUCT><AMOUNT>3980</AMOUNT><PRODUCT_NAME>Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-1990</AMOUNT><PRODUCT_NAME>Descuento para Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT><PRODUCT><AMOUNT>5980</AMOUNT><PRODUCT_NAME>Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-2990</AMOUNT><PRODUCT_NAME>Descuento para Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT></PRODUCT_DETAIL><RETURN_URL>http://localhost/personas/planesV2/payment</RETURN_URL><SESSION_ID>2023080722154901</SESSION_ID><TOTAL_AMOUNT>34990</TOTAL_AMOUNT><TRANSACTION_IDENTIFIER>2023080722154901</TRANSACTION_IDENTIFIER><TRANSACTION_TIMESTAMP>20230807221549</TRANSACTION_TIMESTAMP><TRANSACTION_TYPE>2</TRANSACTION_TYPE><SOCIETY>PCS</SOCIETY></SHOPPING_CART>";
			//String data = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><SHOPPING_CART><CUSTOMER_ID>17703242-5</CUSTOMER_ID><DELIVERY_AMOUNT>0</DELIVERY_AMOUNT><ORDER_ID>688169198</ORDER_ID><PRODUCT_DETAIL><PRODUCT><AMOUNT>34990</AMOUNT><PRODUCT_NAME>HUAWEI SMARTWATCH WATCH FIT NEGRO, Negro</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>1SW04556</SKU></PRODUCT><PRODUCT><AMOUNT>3980</AMOUNT><PRODUCT_NAME>Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-1990</AMOUNT><PRODUCT_NAME>Descuento para Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT><PRODUCT><AMOUNT>5980</AMOUNT><PRODUCT_NAME>Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-2990</AMOUNT><PRODUCT_NAME>Descuento para Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT></PRODUCT_DETAIL><RETURN_URL>http://localhost/personas/planesV2/payment</RETURN_URL><SESSION_ID>2023080802321201</SESSION_ID><TOTAL_AMOUNT>34990</TOTAL_AMOUNT><TRANSACTION_IDENTIFIER>2023080802321201</TRANSACTION_IDENTIFIER><TRANSACTION_TIMESTAMP>20230808023212</TRANSACTION_TIMESTAMP><TRANSACTION_TYPE>2</TRANSACTION_TYPE><SOCIETY>PCS</SOCIETY></SHOPPING_CART>";
			//String data = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><SHOPPING_CART><CUSTOMER_ID>17703242-5</CUSTOMER_ID><DELIVERY_AMOUNT>0</DELIVERY_AMOUNT><ORDER_ID>688169198</ORDER_ID><PRODUCT_DETAIL><PRODUCT><AMOUNT>34990</AMOUNT><PRODUCT_NAME>HUAWEI SMARTWATCH WATCH FIT NEGRO, Negro</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>1SW04556</SKU></PRODUCT><PRODUCT><AMOUNT>3980</AMOUNT><PRODUCT_NAME>Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-1990</AMOUNT><PRODUCT_NAME>Descuento para Programado Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT><PRODUCT><AMOUNT>5980</AMOUNT><PRODUCT_NAME>Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>PODLV0003</SKU></PRODUCT><PRODUCT><AMOUNT>-2990</AMOUNT><PRODUCT_NAME>Descuento para Express Delivery</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>0</SKU></PRODUCT></PRODUCT_DETAIL><RETURN_URL>http://localhost/personas/planesV2/payment</RETURN_URL><SESSION_ID>2023080813232401</SESSION_ID><TOTAL_AMOUNT>34990</TOTAL_AMOUNT><TRANSACTION_IDENTIFIER>2023080813232401</TRANSACTION_IDENTIFIER><TRANSACTION_TIMESTAMP>20230808132324</TRANSACTION_TIMESTAMP><TRANSACTION_TYPE>2</TRANSACTION_TYPE><SOCIETY>PCS</SOCIETY></SHOPPING_CART>";
			//String data ="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><SHOPPING_CART><CUSTOMER_ID>18787283-9</CUSTOMER_ID><DELIVERY_AMOUNT>0</DELIVERY_AMOUNT><ORDER_ID>688328669</ORDER_ID><PRODUCT_DETAIL><PRODUCT><AMOUNT>251760</AMOUNT><PRODUCT_NAME>Honor X9, 128 GB Negro</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>178010</SKU></PRODUCT></PRODUCT_DETAIL><RETURN_URL>https://portalpreprod.entel.cl/personas/planesV2/payment</RETURN_URL><SESSION_ID>2023080817425301</SESSION_ID><TOTAL_AMOUNT>251760</TOTAL_AMOUNT><TRANSACTION_IDENTIFIER>2023080817425301</TRANSACTION_IDENTIFIER><TRANSACTION_TIMESTAMP>20230808174253</TRANSACTION_TIMESTAMP><TRANSACTION_TYPE>2</TRANSACTION_TYPE><SOCIETY>PCS</SOCIETY></SHOPPING_CART>";
			String data ="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><SHOPPING_CART><CUSTOMER_ID>18787283-9</CUSTOMER_ID><DELIVERY_AMOUNT>0</DELIVERY_AMOUNT><ORDER_ID>688328669</ORDER_ID><PRODUCT_DETAIL><PRODUCT><AMOUNT>251760</AMOUNT><PRODUCT_NAME>Honor X9, 128 GB Negro</PRODUCT_NAME><QUANTITY>1</QUANTITY><SKU>178010</SKU></PRODUCT></PRODUCT_DETAIL><RETURN_URL>https://portalpreprod.entel.cl/personas/planesV2/payment</RETURN_URL><SESSION_ID>2023080817440301</SESSION_ID><TOTAL_AMOUNT>251760</TOTAL_AMOUNT><TRANSACTION_IDENTIFIER>2023080817440301</TRANSACTION_IDENTIFIER><TRANSACTION_TIMESTAMP>20230808174403</TRANSACTION_TIMESTAMP><TRANSACTION_TYPE>2</TRANSACTION_TYPE><SOCIETY>PCS</SOCIETY></SHOPPING_CART>";
			
			//System.out.println("Base64.getDecoder().decode(data):"+new String(Base64.getDecoder().decode(data)));
			System.out.println("data:"+data);
			privKey = getPrivateKeyfromKeyStore(fileRepositorio, "entel123", null, null,"enteleft", "entel123");
			System.out.println("privKey:"+ new String(privKey.getFormat()));
			
			byte[] firma = firmar(privKey, null, data.getBytes());
			System.out.println("firma:"+new String(Base64.getEncoder().encode(firma)));
			
			
			//System.out.println("firma atg:"+new String(firma64));
			
			//firma = Base64.getDecoder().decode(firma64);
			
			//firma="ovt3uYpus5yofsWoP9V5pf4idY9RbI4IAN7WREiQIZO7OIHiSZzhlR8P3Vv5QqKYdmQPrGTGPzTZTTyxyCkC+cZWzPloCxjJtIWRm8NUfHemaofH78S+goRwmPuR44oyQzykE2FPzWPj3Bvi3m++urg0rQfvM8vzn09p/1tp5Trudt+WdAQ6WN8zm94ail3nmeRtvEub2BEW7GUtgYDc9iZqSI4mtqp2+VjtnuT/eNZBdkZQhqTNfMEpF4vtgdAKt9DdXksIArldlSkj+H+9DgrOkUbkiR44jlUdEjjv/Sb6DVelzhUqYBg0y254KEU6tnbWv/Zpr0G+brXSXhv2xg==".getBytes("UTF-8");
			       //ovt3uYpus5yofsWoP9V5pf4idY9RbI4IAN7WREiQIZO7OIHiSZzhlR8P3Vv5QqKYdmQPrGTGPzTZTTyxyCkC+cZWzPloCxjJtIWRm8NUfHemaofH78S+goRwmPuR44oyQzykE2FPzWPj3Bvi3m++urg0rQfvM8vzn09p/1tp5Trudt+WdAQ6WN8zm94ail3nmeRtvEub2BEW7GUtgYDc9iZqSI4mtqp2+VjtnuT/eNZBdkZQhqTNfMEpF4vtgdAKt9DdXksIArldlSkj+H+9DgrOkUbkiR44jlUdEjjv/Sb6DVelzhUqYBg0y254KEU6tnbWv/Zpr0G+brXSXhv2xg==
			//String firmaAmbLocal = "TukY0x16YLh29ScFTeho1ezR4qxY31fIRaDoWD3nH4Ovm8vCPFDzL+SMaaN8nBvOdvkZ4KJzIm346s3KlqkOwm0KwzOg21ksinyMxUjEcLHLeZC6zeeloPg6lFmW5n5i28ittTXRfwKW0dOn8SIl5P6u0RH7+MQJOCv1XyW4fgrCS9IghPSopjKBOusWZls0J6oeo5gg/adwN9HaFSvddnwmNlrElb4GtLQ8Fsc+cY5MD+ghYve1kemC9XCq2nGZJDv4n+JUgea0yGdnusdCkqh2C8euuITBCvKE2mfErS85x3ERgKBfg1olh+DE5v3t8p4eJt19N5T07qhg+4rH1A==";
			//String firmaAmbLocal = "KLRC7rrSKljskuhmjZm77NEDBiOPqqACme7zuppvj3zqrdkoZOyiZ8m5Hkeg1izqrhAUmf1lynxqH9sT1hE8fyucMpgaJACs+fwlxG1ptKhsUPgCpA2+JBsNWHb16Ze+n3HUUcdHOQMkxytW5gN6CdREgwwkMeU464VgBd/k0Tw18saZYB/mav5iwBXpAFi5HQrRWmtXLGPjJH9nz5RY8O9dtVASsbd4kUyfLR6Sbj6iEywXBgLqiDYL5HNU4StvkjMN7CpOu99TPlnClHTHGsKPquppSJJwKTceMtiZc1paSIr374mAmgqPNwVcwYGiJC8auSwdgYZ2O5s43AdLsw==";
			//String firmaAmbLocal = "XptM4/5MC51KJcvyvbVe7iHs/ra0Pge1ok8GXnmDgxyAOoxKm+VfxeIToU8tpjJ61HbZ8sF6roiihujF0gPKtW7NpKlEZCzaSXC7bGJdRCngNQ/GsnWCF8e1LT7ephodZ6+tSID9Hth4X2hYBUcTpBboQi2kbAlezdm2ewuyOsnWPk8437ZvmloTIDj2HGvEbMavgEwGj09J2VKafG2VcW0WotT2WRUwEi/21SZ5BQbI/h0i6v7P0Q5mzRof0qWkLWg8tSbLMtcFji9EbwmxZuGXf1leR5XRAl1NxcYCzc/n3a5dLWlhx49XS2PRvIRF0SxmmDRYe8vuDjyLKoOh+A==";
			//String firmaAmbLocal = "BX0pMxKNf9nKpc8Wo05qgUMmOYW58sLiSRg1ldV08tfDpP8jh6BLuogOpcwctxO1gJOUBX7gG0dgaP1tB9cpCJbDaBE6YHOVwDysDjjSZq7kFrW3PQ6dVdaG+J34Qk3Whv4FpjlT/+m2sPDq9VJ3nE4vfhg0QnWWG7/J4OvjtYWI+QP7gN2iMnc87zJulKJtzGN5dPc2fg+NhWMc8DflpJcmK/W1MoZ4OeKIBCHNPy7ePHTHWF/oI6N9kzHwQ/uNjSWRqCIQs1mp2e7X1BDST3xhj2OZNpDIr5e51wg/d2Kpxeecfwq7xKwRLAXqIQo+MkcVoSTzGzl77RDyxxMi+w==";
			//String firmaAmbLocal = "nhbxsXqn5bwXCrvYP5vgKs9mrPbmEqbLT1LoQocUT2M8EAWcOx15aHCg1uSiQ1CQ3EyLhytoPK+lyb5v5IDdpaPnXX3VMFVsapzSM+lH7hcfyjN3XzWjcIjVR+bFcvA0Yj3JVAwcbgA8HAjskO53O56VCFTBmndgVP6Qk8UGfnlMvGDL9bGIF+TckAPc4sRlTWj8uqpQm0oMNaibWpDS4DP5JvQPpTyuE313GtwLLRH7txcIDxlBKRAFYtKeeWozfXX1lDtU+KEjbp0UfLi7J472FeKtVcHzuyPoDfasY/j3pkGN2HYJBJ3NxbVbP9PBf69Nt4JKwFWLN69H6hUhvg==";
			String firmaAmbLocal = "L11eHsVYsi8Y9tud7ys9cuvidaE4c+ZDtrURUlkHUh37XcGmhikSx5BC4O5QpEm0aYkZuukpVCPqyzH6rY3XpKnhb2HyDQrSS1ova8nr1loM6ov2L7LcXueKpG0Prl53Hr9zE+TyVA3CFhwilJtZuBz1CpLhGLQWoBny9aZ3yRTTnxmHotT6DRTsw+rpjhjD2dv/5igRlvCbR3FjxhJ31MYuQXXoOFOl6qkdBBwc8A2Tgnvz1ViYi/QqNZyl957Bg2o2z4FND3ln9Hst2pEYhSjcGsdAmplg9tyWjVS0VA5H/fpZo9TSkrUpMPv0ONjl66HufWIyr02nOPZFFqPWDQ==";
			
			System.out.println("Firmas son iguales???"+firma.toString().equals(firmaAmbLocal));
			
			firma = Base64.getDecoder().decode(firmaAmbLocal);
			System.out.println("firma ambienteLocaL:"+new String(firmaAmbLocal));
			
			
			KeyStore ks = KeyStore.getInstance("JKS");
			ks.load(new FileInputStream(fileRepositorio),"entel123".toCharArray());
			Boolean b = validar(ks, "enteleft", "",data.getBytes("UTF-8"), firma);
			System.out.println("validado:"+b);
			

		}catch(Exception e) {
			System.out.println("Error:"+ e);
		}
		
		
		
	}
	
	
	
}
